In [1]:
import numpy as np
import random

In [60]:
def forwards(x,a):
    y = np.tanh((w @ x) - b) # forward vector


# loss function
def loss(y_pred,y):
    return np.square(y_pred - y).sum()

# gradient of the loss function
def gradient(y_pred,y):
    return 2 * (y_pred - y)


def gradients(x,y):
    nablaw = [np.zeros(x.shape) for x in w]
    inputv = x
    return w - eta * nw 
'''
def sigmoidal(x):
    return 1/(1+np.exp(-x))
'''


# vector / matrix template size
mat = [4,4]
eta = 1e-3 # learning rate

# w = [np.random.randn(x,y) for y,x in zip(mat[1:], mat[:1])] # creates a weight matrix
w = np.random.rand(4,4)
b = np.random.randn(4) # bias / threshold vector

x = np.array([1,2,3,4]) # input vector

w2 = np.arange(16).reshape(4,4) 

print(w,x)
print(type(w), type(b), type(x))
print(w @ x) # @ = np.matmul(w,x)
print(w2, x)
print(w2 @ x)

# [6.03303574 4.60467303 4.25774192 3.78438018]
a = 0.12834535 + 2 *0.8752226 + 3 * 0.29858739 + 4 * 0.81462076



[[0.19591732 0.7614969  0.27040998 0.51141374]
 [0.41043887 0.31385362 0.56901488 0.72533251]
 [0.64759512 0.52224548 0.35826636 0.12203733]
 [0.60160401 0.4646149  0.68779426 0.75190026]] [1 2 3 4]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[4.57579603 5.64652077 3.25503447 6.60181762]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] [1 2 3 4]
[ 20  60 100 140]
